jelly_power/urls.py
from django.contrib import admin
from django.urls import include, path
from staticpages import views

urlpatterns = [
    path('', include('staticpages.urls')),
    path('mypage/',include('mypage.urls')),
    path('shop/', include('shop.urls')),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
]

news/urls.py
from django.urls import path
from . import views


app_name = "news"
urlpatterns = [
path('',views.news_main,name="news_main"),
path('<int:newsId>/', views.news_views, name="news_views"),

#path('<int:pk>/comments/new/',views.comment_new),

        ]

news/models.py
from django.db import models
# Create your models here.
from django.utils import timezone


class News(models.Model):
    news_id = models.IntegerField(primary_key=True, auto_created=True)
    news_title = models.CharField(max_length=100)
    news_text = models.TextField()
    news_created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.news_title

class NewsImg(models.Model):
    img_id = models.IntegerField(primary_key=True, auto_created=True)
    img_news = models.ForeignKey(News, on_delete=models.CASCADE)
    img_item = models.ImageField(blank=True, null=True)

class Comment(models.Model):
    com_post = models.ForeignKey(News, on_delete=models.CASCADE)
    com_text = models.TextField()
    com_author = models.CharField(max_length=10)
    com_created_date = models.DateTimeField(auto_now_add=True)

news/forms.py
from django import forms
from news.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields= ('com_author','com_text')

news/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render
from news.models import News


def news_main(request):
    news_list = News.objects.all()
    return render(request, "news/news_main.html", {"news_list": news_list, })


def news_views(request, newsId):
    try:
        news = News.objects.get(pk=newsId)
    except News.DoesNotExist:
        raise Http404("News does not exist")
    return render(request, "news/news_views.html", {"news": news})

news/templates/news/news_main.html
{% extends 'staticpages/base.html' %}


{% block content %}

<style>
    .news-list{
        list-style-type: none;
        overflow: hidden;
    }
    .news-item{
        float: left;
        margin: 20px 30px 20px 30px;
        text-align: center;
    }
        .news-title{
        width: 250px;
        height: 20px;
    }

    .news-item a:link, .news-item a:visited, .shop-item a:link, .shop-item a:visited{
        color: black;
        text-decoration: none;
    }

    .news-item a:active, .news-item a:hover, .shop-item a:active, .shop-item a:hover{
        color: black;
        text-decoration: underline;
    }
</style>

<div>
    <p>what's new</p>
    <div>
        <div>화살표</div>
        <div>
            <div>사진</div>
            <div>뉴스 글</div>
        </div>
        <div>화살표</div>
    </div>
</div>

    <div class="news-highlight" style="display: table; margin-left: auto; margin-right: auto;">
    <div class="main-shortcut"><a href=""><h2>What's New</h2></a></div>
    <ul class="news-list" >
        <li class="news-item"><a href="">
            <img class="news-thumbnail" width=250px height=250px src="http://thumbnail.egloos.net/600x0/http://pds21.egloos.com/pds/201210/10/68/f0163868_507576441e014.jpg">
            <p><span class="news-title">hihi news1</span></p></a></li>

        <li class="news-item"><a href="">
            <img class="news-thumbnail" width=250px height=250px src="http://thumbnail.egloos.net/600x0/http://pds21.egloos.com/pds/201210/10/68/f0163868_507576441e014.jpg">
            <p><span class="news-title">hihi news2</span></p></a></li>

        <li class="news-item"><a href="">
            <img class="news-thumbnail" width=250px height=250px src="http://thumbnail.egloos.net/600x0/http://pds21.egloos.com/pds/201210/10/68/f0163868_507576441e014.jpg">
            <p><span class="news-title">hihi news3</span></p></a></li>
    </ul>

</div>

<div></div>


<!--
<style>
    .news-thumbnail{
        border-style: solid;
        border-color: black;
        border-width: 2px;
    }

    .news-item{
        float:left;
        margin: 40px;
    }

    .news-list{
        display: inline-block; width:90%; margin: 0 auto;
    }
</style>

<div style="list-style: none; display: table; margin-left: auto; margin-right: auto;text-align: center">
    {% if news_list %}

          <ul class="news-list">
              {% for news in news_list %}


        <li class="news-item" style ="height: 400px;">
        <div class="news-thumbnail"><a href="{{ news.news_id }}/"><img src="{{news.news_thumbnail}}" width ="300" height="300"></a></div>
        <div>
            <a href="{% url 'news:news_views' news.news_id %}"><span class="news-title">{{news.news_title}}</span></a>
            <p><span class="news-summary">{{news.news_text}}</span></p>
        </div>
    </li>
              {% endfor %}
          </ul>
      {% else %}
          <p>No Data.</p>

    {% endif %}

</div>

-->
{% endblock %}

news/templates/news/news_views.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>news_details</title>
</head>
<body>

<h1>{{ news.news_title }}</h1>
<p>{{ news.news_text }}</p>


</body>
</html>